# NUMPY 

1. NumPy atau Numpy adalah library aljabar linear untuk Python 
2. Numpy sering dipakai dalam konteks AI dan data Science
3. Numpy sangat cepat dan dibangun melalui bahasa C

CARA ISNTALL NUMPY

Anaconda prompt -> conda install numpy

In [1]:
import numpy as np 

In [2]:
angka = [1,2,3]

In [3]:
angkap1 = np.array(angka)

In [4]:
angkap1

array([1, 2, 3])

In [6]:
angkap1*3

array([3, 6, 9])

In [7]:
versilist = [[1,2,3],[4,5,6],[7,8,9]]
versilist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
versinumpy = np.array(versilist)
versinumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#menentukan angka awal dan angka akhir

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#memberikan jarak (angka awal, angka akhir, dan jarak )

np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [16]:
#memunculkan angka nol sesuai dengan yang kita inginkan

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
#np zeros dengan menggunakan matriks 2 dimensi 

np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
#memunculkan angka 1 

np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
#np zeros dengan menggunakan matriks 2 dimensi 

np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
#memunculkan array 1 dimensi dari awal sampai akhir dengan angka yang ditentukan dan jarak bisa ditentukan

np.linspace(0,8,10) #artinya ingin membuat array dari 0 sampai 8 dan akan dipecah sampai 10.

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

## Identity Matrix 

adalah sebuah matrix dua dimensi 

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])