## Numpy

In [1]:
import numpy as np

In [5]:
angka = [1,2,3]

In [6]:
angkanp = np.array(angka)

In [7]:
angkanp

array([1, 2, 3])

In [8]:
angkanp*3

array([3, 6, 9])

In [10]:
versilist = [[1,2,3],[4,5,6],[7,8,9]]
versilist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
versinumpy = np.array(versilist)
versinumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.linspace(0,8,15)

array([0.        , 0.57142857, 1.14285714, 1.71428571, 2.28571429,
       2.85714286, 3.42857143, 4.        , 4.57142857, 5.14285714,
       5.71428571, 6.28571429, 6.85714286, 7.42857143, 8.        ])

## Identity Matrix

In [30]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])