## bilangan distribusi uniform (angka 0-1)


In [2]:
import numpy as np

In [3]:
np.random.rand(7)

array([0.4112214 , 0.61334657, 0.63801987, 0.64168044, 0.64164754,
       0.83974216, 0.75658023])

In [4]:
#bilangan distribusi uniform (angka 0-1) matriks 2 dimensi 

np.random.rand(5,4) 

array([[0.71717064, 0.44283689, 0.27538047, 0.0597277 ],
       [0.99350648, 0.63357462, 0.89546983, 0.12521398],
       [0.54272208, 0.53729193, 0.98383169, 0.62354054],
       [0.37148976, 0.49452314, 0.72540022, 0.3865779 ],
       [0.63322716, 0.9789541 , 0.84636271, 0.92703464]])

In [5]:
#menggunakan distribusi normal (gaussiab)

np.random.rand(10)

array([0.91443472, 0.84849548, 0.76591354, 0.19518425, 0.39723994,
       0.27181405, 0.1925814 , 0.32092077, 0.22396093, 0.07129775])

In [6]:
#menggunakan distribusi normal (gaussian) 2 dimensi

np.random.rand(4,4)

array([[0.72696065, 0.73615546, 0.33187397, 0.17175839],
       [0.55234974, 0.53760569, 0.04627725, 0.66089861],
       [0.26760982, 0.22740852, 0.39297133, 0.41875767],
       [0.44690755, 0.16684303, 0.28792857, 0.33714588]])

In [8]:
#cara cepat menulis np.random.rand

from numpy.random import randn


In [10]:
randn(6,2)

array([[ 0.58720848, -0.44223202],
       [ 1.1456279 , -1.14451104],
       [ 0.67170058,  0.52967949],
       [-0.03736029,  0.36218624],
       [ 1.08225001, -1.28094851],
       [ 0.98826639,  0.02777689]])

In [11]:
#megenaerate sebuah integer bisa menggunakan

from numpy.random import randn, randint

In [12]:
randint(0,10)

5

In [13]:
#jika ingin munculkan angka integer

randint(0,10,5)

array([6, 6, 6, 2, 5])

In [14]:
bilangan = randint(0,100,20)

In [15]:
bilangan

array([70, 17, 98, 74, 55, 22, 34,  3, 33, 71, 88, 66, 39, 86, 91, 30, 70,
        6, 92, 52])

In [16]:
#mengubah 1 dimensi (reshape)

bilangan.reshape(2,10)

array([[70, 17, 98, 74, 55, 22, 34,  3, 33, 71],
       [88, 66, 39, 86, 91, 30, 70,  6, 92, 52]])

In [17]:
from numpy.random import randn, randint

In [21]:
randint(0,10,25)

array([9, 5, 2, 2, 4, 0, 0, 4, 5, 0, 6, 8, 1, 9, 6, 3, 1, 7, 4, 3, 0, 6,
       9, 7, 4])

In [24]:
coba = randint(0,10,20).reshape(5,4)


In [23]:
coba

array([[4, 0, 3, 8, 5],
       [0, 4, 4, 0, 4],
       [8, 0, 0, 5, 6],
       [1, 1, 0, 1, 7],
       [0, 7, 4, 0, 3]])

In [25]:
coba.reshape(2,10)

array([[9, 5, 4, 1, 0, 8, 0, 2, 1, 9],
       [7, 4, 3, 3, 3, 3, 7, 3, 2, 3]])

In [26]:
coba = coba.reshape(2,10)

In [27]:
coba

array([[9, 5, 4, 1, 0, 8, 0, 2, 1, 9],
       [7, 4, 3, 3, 3, 3, 7, 3, 2, 3]])

In [45]:
# Membuat matriks 1 dimensi dan 2 dimensi 

coba1d = randint(0,100,20)

In [46]:
coba2d = randint(0,10,20).reshape(4,5)


In [47]:
coba1d

array([29, 39, 96,  8, 14, 71, 59, 91, 54, 42, 18, 45, 56, 65, 28, 12, 65,
       44, 43, 97])

In [48]:
coba2d

array([[3, 6, 7, 5, 5],
       [9, 8, 3, 8, 9],
       [7, 9, 1, 8, 9],
       [0, 9, 0, 5, 0]])

In [49]:
#mencari angka maksimal

coba1d.max()

97

In [50]:
coba2d.max()

9

In [51]:
coba1d.min()

8

In [52]:
coba2d.min()

0

In [55]:
#Mengindex dengan argmax dan argmin sangat penting dalam AI harus mencari nilai tertinggi dan trenedah

coba1d.argmax()

19

In [54]:
coba2d.argmin()

15

In [56]:
#mencari tahu dimensi array dengan shape

coba1d.shape


(20,)

In [57]:
coba2d.shape

(4, 5)

In [58]:
#mengetahui tipe data dengan dtype

coba1d.dtype

dtype('int32')

In [59]:
coba2d.dtype

dtype('int32')

# Indexing di Numpy

In [61]:
import numpy as np

In [62]:
coba = np.arange(0,11)

In [67]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
coba[6]

6

In [69]:
# Slicing

coba[5:1]

array([], dtype=int32)

In [70]:
coba[5:9]

array([5, 6, 7, 8])

In [71]:
coba[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
coba2 = coba[:6]

In [73]:
coba2

array([0, 1, 2, 3, 4, 5])

In [ ]:
#

## Latihan Numpy 

In [3]:
import numpy as np

In [4]:
np.random.rand(7)

array([0.83674753, 0.98225201, 0.91136118, 0.690777  , 0.89517896,
       0.53886999, 0.75874798])

In [5]:
np.random.rand(5,4)

array([[0.63356124, 0.69983053, 0.58521292, 0.80840702],
       [0.8659042 , 0.51632663, 0.55406031, 0.71882392],
       [0.5230915 , 0.99106325, 0.65193651, 0.39683228],
       [0.19055279, 0.37164174, 0.89358613, 0.09651761],
       [0.17412748, 0.44532542, 0.43549242, 0.40268487]])

In [6]:
# Menggunakan bilangan distribusi normal(gaussian)
np.random.randn(10)

array([-0.1945284 , -1.89714724, -2.53889947, -1.28229261, -0.29858804,
       -0.02817514,  0.69105133,  0.66822947,  1.11640724, -1.81707492])

In [7]:
# Menggunakan bilangan distribusi normal(gaussian) matrik 2 dimensi 
np.random.randn(4,4)

array([[-1.01894526,  0.19350627,  0.32392083, -0.36065996],
       [-1.09987733,  0.78140779, -0.17337909, -0.82866338],
       [-0.67230229,  1.97460388,  0.46296316, -0.16912623],
       [-1.01561013,  0.23252789, -0.79082309,  0.10158957]])

In [8]:
from numpy.random import randn

In [9]:
randn(8,6)

array([[-0.43513838,  0.57170414, -0.44455755, -1.05781106,  0.17375114,
        -0.46737652],
       [ 0.98118684,  0.41946772, -0.8084871 , -1.01888178, -0.89166156,
        -0.03220515],
       [ 1.64596567, -0.28264869, -0.06572677, -0.04766558,  0.8707995 ,
        -0.54100139],
       [-0.64642196,  0.80284869, -1.15030304,  1.28578988,  0.15091986,
        -1.16849883],
       [ 0.99812054, -0.06029169,  2.22846876, -1.34511782, -1.36248706,
         0.19698326],
       [-0.34387798, -0.44230839,  0.01027846, -0.65636904,  0.12180202,
         0.15313036],
       [-1.85445403, -0.93833804, -1.45913181, -1.22320777, -1.55700703,
         0.18412068],
       [-2.56681122, -0.02043932, -0.38773057, -0.89757922, -0.39978305,
         0.02495336]])

In [12]:
from numpy.random import randn, randint

In [11]:
randn(4,6)

array([[ 0.72525808, -0.84006503,  0.89343516, -0.6668085 ,  0.52583471,
         0.32033577],
       [-1.36959966, -1.53272843,  0.1621407 , -1.19348633, -0.9295508 ,
         1.52530899],
       [-0.27799028, -0.04378551,  0.42852598, -0.31729923,  0.16927724,
        -0.45769073],
       [-0.66507626,  0.05271534,  0.3328584 ,  0.13304071,  0.32417839,
         0.67876378]])

In [13]:
randint(0,45)

36

In [15]:
randint(0,45,6)

array([40, 40, 29, 16, 36,  7])

In [16]:
bilangan = randint(0,100,20)

In [17]:
bilangan

array([83, 61, 38, 66, 82, 24, 94,  4, 13, 47, 62, 45, 45, 86, 37, 45, 64,
       84, 17, 15])

In [18]:
bilangan.reshape(4,5)

array([[83, 61, 38, 66, 82],
       [24, 94,  4, 13, 47],
       [62, 45, 45, 86, 37],
       [45, 64, 84, 17, 15]])

In [25]:
randint(0,10,20).reshape(5,4)

array([[3, 1, 3, 7],
       [7, 7, 5, 9],
       [5, 0, 8, 5],
       [4, 6, 6, 3],
       [8, 9, 5, 2]])

In [26]:
item = randint(0,10,20).reshape(5,4)

In [27]:
item 

array([[5, 3, 2, 7],
       [9, 7, 4, 2],
       [5, 5, 9, 4],
       [6, 3, 8, 9],
       [7, 5, 9, 9]])

In [29]:
item.reshape(5,4)

array([[5, 3, 2, 7],
       [9, 7, 4, 2],
       [5, 5, 9, 4],
       [6, 3, 8, 9],
       [7, 5, 9, 9]])

In [31]:
latihan1 = randint(0,200,20)

In [35]:
latihan2d = randint(0,200,20).reshape(4,5)

In [34]:
latihan1

array([118, 195,  11,  73, 112, 112,  85, 142, 124, 125,  55,  60,  87,
        50,  18, 150, 126, 109, 141,  87, 138,  82, 193,  40,  75, 154,
       151, 117, 116, 151])

In [36]:
latihan2d

array([[119, 134, 191,  72,  83],
       [ 88, 126,  41, 172,  78],
       [111, 102,  22, 180,  57],
       [  8,  35,  85, 153,  27]])

In [38]:
#umencari nilai maksimal mnggunakan fungsi max
latihan1.max()

195

In [39]:
latihan1.max()

195

In [40]:
latihan2d.min()

8

In [41]:
latihan2d.max()

191

In [42]:
latihan1.min()

11

In [44]:
latihan2d.reshape(4,5)

array([[119, 134, 191,  72,  83],
       [ 88, 126,  41, 172,  78],
       [111, 102,  22, 180,  57],
       [  8,  35,  85, 153,  27]])

In [45]:
#mencari indeks dengan arg max
latihan1.argmax()

1

In [46]:
latihan2d.argmax()

2

In [47]:
latihan1.argmin()

2

In [49]:
latihan1.shape

(30,)

In [50]:
latihan2d.shape

(4, 5)

In [51]:
latihan1.dtype

dtype('int32')

## Indexing Numpy


In [58]:
latihan = np.arange(0,11)

In [59]:
latihan

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
latihan[5]

5

In [61]:
latihan[5:]

array([ 5,  6,  7,  8,  9, 10])

In [62]:
latihan[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
latihan[6:10]

array([6, 7, 8, 9])

In [65]:
latihan[5:9]

array([5, 6, 7, 8])

In [66]:
latihan[:6]

array([0, 1, 2, 3, 4, 5])

In [67]:
latihan[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
latihan[4:6:5]

array([4])

In [69]:
latihan_deux = latihan[:3]

In [70]:
latihan_deux

array([0, 1, 2])

In [75]:
latihan3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [76]:
latihan3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
latihan3[0][3]

4

In [81]:
latihan3[1][2]

7

In [82]:
latihan3[2][1]

10

In [83]:
latihan3[1]

array([5, 6, 7, 8])

In [84]:
latihan3[2]

array([ 9, 10, 11, 12])

In [85]:
latihan3[2,2]

11

In [86]:
latihan3[2:3,0:1]

array([[9]])

In [88]:
latihan3[2:3,3:]

array([[12]])

## Slicing dengan Boolean 

In [92]:
bil = np.arange(1,11)

In [93]:
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
angka_ini = bil < 4

In [95]:
angka_ini

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [98]:
angka_ini = bil[angka_ini]

In [99]:
angka_ini

array([1, 2, 3])

In [100]:
bil = np.arange(1,11)

In [101]:
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
bil[bil<5]

array([1, 2, 3, 4])

In [103]:
bil[bil>7]

array([ 8,  9, 10])

In [104]:
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bil