# Operasi di Numpy

In [4]:
import numpy as np

In [2]:
coba = np.arange(0,11)

In [3]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
coba+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
coba+78

array([78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88])

In [7]:
coba+coba

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
coba_list = [0,1,2,3,4,5,6,7,8,9,10]

In [13]:
coba_list+coba_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
coba*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
coba_list*3

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10]

In [16]:
# Pengurangan 

coba-coba

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
coba-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [1]:
#invalid karena angka 1 tidak bisa dibagi
coba/coba

NameError: name 'coba' is not defined

In [19]:
1/coba

<ipython-input-19-021fa7643746>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/coba


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [20]:
#operasi matematika akar

np.sqrt(coba)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [21]:
# nilai exponensial 

np.exp(coba)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [22]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
#mencari nilai meksimal 

np.max(coba)

10

In [24]:
# atau mencari nilai maksimal
coba.max()

10

In [25]:
#mencari nilai minimal 

np.min(coba)

0

In [26]:
#atau 

coba.min()

0

In [27]:
#Mencari nilai sin

np.sin(coba)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [28]:
#Mencari nilai logaritmik 

np.log(coba)

<ipython-input-28-64e7abefc511>:3: RuntimeWarning: divide by zero encountered in log
  np.log(coba)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Bisa mencari di Website Numpy.ord/doc

## Operasi Numpy

In [2]:
import numpy as np

In [3]:
num = np.arange(0,11)

In [4]:
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
num + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
num + num

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
num*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [9]:
num-num

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
num - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [11]:
1/num

C:\Users\Lenovo\AppData\Local\Temp/ipykernel_3600/3328592121.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/num


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [13]:
np.sqrt(num)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [14]:
np.square(num)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [15]:
np.sqrt(num)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [17]:
#nilai exponen : 2.7182
np.exp(num)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [18]:
num.max()

10

In [19]:
num.min()

0

In [21]:
np.sin(num)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])