In [1]:
import numpy as np

In [5]:
# Contoh bilangan distribusi uniform yaitu bilangan bilangan 0 sampai 1 
np.random.rand(9)

array([0.02085911, 0.76181354, 0.18029867, 0.87481979, 0.36205683,
       0.69433855, 0.69178443, 0.01207319, 0.27239104])

In [6]:
#bilangan distribusi uniform (0-1) matriks 2 dimensi 
np.random.rand(5,5)

array([[0.86049438, 0.18137455, 0.40129103, 0.56006718, 0.72050953],
       [0.7138926 , 0.64201701, 0.67493633, 0.88987745, 0.05937974],
       [0.87503961, 0.42812778, 0.43596006, 0.63286023, 0.04444766],
       [0.80878407, 0.59055108, 0.35255722, 0.71990387, 0.18205046],
       [0.47402849, 0.52845388, 0.18483529, 0.71695452, 0.665963  ]])

In [7]:
#Bilanagan distribusi Normal
np.random.randn(10)

array([ 1.53210779,  1.88098619,  0.76545902, -1.02740861, -0.99950291,
        0.18587187, -1.32348984, -0.9583668 , -1.49292251,  0.31906584])

In [8]:
#bilangan distribusi normal matriks 2 dimensi 
np.random.randn(4,4)

array([[ 0.4780147 , -0.82570044, -0.43649375, -0.01876624],
       [ 0.58428925, -0.54375764, -0.60880415,  1.30732454],
       [-0.56968304,  0.67131218, -0.16621052, -0.61220161],
       [ 1.0235308 , -0.82061047, -0.88494184,  0.11690665]])

In [10]:
 # atau dibuat sederhana seperti ini
from numpy.random import randn

In [11]:
randn(6,3)

array([[-1.06452888,  0.28959855,  0.51855074],
       [-1.59700881, -1.31327413,  0.48304197],
       [ 0.91190364,  0.63487429,  1.40886091],
       [-1.77184241, -2.00592987, -1.17225186],
       [-2.00751359, -0.34723566, -1.56641916],
       [ 0.32314466,  1.34972932, -0.09614429]])